-- Northstar Check is a fictional scam-awareness survey.
create table if not exists public.demo_submissions (
  id bigint generated by default as identity primary key,
  name text check (name is null or char_length(trim(name)) between 1 and 100),
  scenario_response text not null check (scenario_response in (
    'Open the link to check',
    'Check the official app or website',
    'Reply to ask for details',
    'Delete it immediately'
  )),
  warning_sign text not null check (warning_sign in (
    'Unexpected request',
    'Pressure to act now',
    'Unusual link or sender',
    'More than one of these'
  )),
  password_example text not null check (password_example in (
    'Banana-Pants-42!',
    'Platypus-Dance-88!',
    'Toast-Wizard-17!',
    'I-Do-Not-Share-Passwords!'
  )),
  location text check (location is null or char_length(trim(location)) between 1 and 100),
  created_at timestamptz default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'demo_submissions'
      and column_name = 'selected_demo_password'
  ) then
    alter table public.demo_submissions add column if not exists scenario_response text;
    alter table public.demo_submissions add column if not exists warning_sign text;
    update public.demo_submissions
    set scenario_response = 'Open the link to check',
        warning_sign = 'Unexpected request'
    where scenario_response is null or warning_sign is null;
    alter table public.demo_submissions alter column scenario_response set not null;
    alter table public.demo_submissions alter column warning_sign set not null;
    alter table public.demo_submissions alter column name drop not null;
    alter table public.demo_submissions alter column location drop not null;
    drop policy if exists "Audience can submit demo entries" on public.demo_submissions;
    alter table public.demo_submissions drop column selected_demo_password;
    alter table public.demo_submissions
      add constraint demo_submissions_scenario_response_check check (scenario_response in (
        'Open the link to check',
        'Check the official app or website',
        'Reply to ask for details',
        'Delete it immediately'
      ));
    alter table public.demo_submissions
      add constraint demo_submissions_warning_sign_check check (warning_sign in (
        'Unexpected request',
        'Pressure to act now',
        'Unusual link or sender',
        'More than one of these'
      ));
  end if;
end $$;

do $$
begin
  alter table public.demo_submissions add column if not exists password_example text;
  update public.demo_submissions
  set password_example = 'I-Do-Not-Share-Passwords!'
  where password_example is null;
  alter table public.demo_submissions alter column password_example set not null;
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.demo_submissions'::regclass
      and conname = 'demo_submissions_password_example_check'
  ) then
    alter table public.demo_submissions
      add constraint demo_submissions_password_example_check check (password_example in (
        'Banana-Pants-42!',
        'Platypus-Dance-88!',
        'Toast-Wizard-17!',
        'I-Do-Not-Share-Passwords!'
      ));
  end if;
end $$;

alter table public.demo_submissions enable row level security;

revoke all on public.demo_submissions from anon, authenticated;
grant insert (name, scenario_response, warning_sign, password_example, location) on public.demo_submissions to anon, authenticated;
grant select on public.demo_submissions to authenticated;

drop policy if exists "Audience can submit survey responses" on public.demo_submissions;
create policy "Audience can submit survey responses"
  on public.demo_submissions for insert
  to anon, authenticated
  with check (
    scenario_response in (
      'Open the link to check',
      'Check the official app or website',
      'Reply to ask for details',
      'Delete it immediately'
    )
    and warning_sign in (
      'Unexpected request',
      'Pressure to act now',
      'Unusual link or sender',
      'More than one of these'
    )
    and password_example in (
      'Banana-Pants-42!',
      'Platypus-Dance-88!',
      'Toast-Wizard-17!',
      'I-Do-Not-Share-Passwords!'
    )
  );

drop policy if exists "Authenticated presenters can view entries" on public.demo_submissions;
create policy "Authenticated presenters can view entries"
  on public.demo_submissions for select
  to authenticated
  using (true);

do $$
begin
  alter publication supabase_realtime add table public.demo_submissions;
exception when duplicate_object then null;
end $$;