-- SCAM Insurance classroom simulation: these are fictional demo values only.
create table if not exists public.demo_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 100),
  selected_demo_password text not null check (selected_demo_password in (
    'DEMO-PASS-01', 'DEMO-PASS-02', 'DEMO-PASS-03', 'DEMO-PASS-04', 'DEMO-PASS-05'
  )),
  location text not null check (char_length(trim(location)) between 1 and 100),
  created_at timestamptz default now()
);

alter table public.demo_submissions enable row level security;

revoke all on public.demo_submissions from anon, authenticated;
grant insert (name, selected_demo_password, location) on public.demo_submissions to anon, authenticated;
grant select on public.demo_submissions to authenticated;

drop policy if exists "Audience can submit demo entries" on public.demo_submissions;
create policy "Audience can submit demo entries"
  on public.demo_submissions for insert
  to anon, authenticated
  with check (selected_demo_password in ('DEMO-PASS-01', 'DEMO-PASS-02', 'DEMO-PASS-03', 'DEMO-PASS-04', 'DEMO-PASS-05'));

drop policy if exists "Authenticated presenters can view entries" on public.demo_submissions;
create policy "Authenticated presenters can view entries"
  on public.demo_submissions for select
  to authenticated
  using (true);

do $$
begin
  alter publication supabase_realtime add table public.demo_submissions;
exception when duplicate_object then null;
end $$;